# Generated by Django 5.2.11 on 2026-02-23 01:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AwarenessProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition & Healthy Eating"),
                            ("hygiene", "Postnatal Hygiene"),
                            ("mental_health", "Maternal Mental Health"),
                            ("vaccination", "Childhood Vaccinations"),
                        ],
                        max_length=50,
                    ),
                ),
                ("event_datetime", models.DateTimeField()),
                ("location", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True)),
                (
                    "attendees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="awareness_programs",
                        to="accounts.motherprofile",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Awareness Program",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HospitalConsultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField()),
                ("symptoms", models.JSONField(blank=True, default=list)),
                ("recommendation", models.TextField(blank=True)),
                ("reference_id", models.CharField(blank=True, max_length=30)),
                ("is_synced", models.BooleanField(default=False)),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultations",
                        to="accounts.motherprofile",
                    ),
                ),
                (
                    "referred_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="referrals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hospital Consultation",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ANCVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visit_number", models.PositiveIntegerField(default=1)),
                ("visit_date", models.DateField(auto_now_add=True)),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=5, null=True
                    ),
                ),
                ("blood_pressure", models.CharField(blank=True, max_length=20)),
                ("symptoms", models.JSONField(blank=True, default=list)),
                ("has_danger_signs", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anc_visits",
                        to="accounts.motherprofile",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "ANC Visit",
                "verbose_name_plural": "ANC Visits",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("mother", "visit_number")},
            },
        ),
    ]
