# Generated by Django 5.2.8 on 2026-02-23 02:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('mother', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('sos', 'Emergency SOS'), ('high_risk', 'High Risk'), ('missed', 'Missed Appointment'), ('system', 'System Update')], default='high_risk', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_resolved', models.BooleanField(default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_alerts', to=settings.AUTH_USER_MODEL)),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.motherprofile')),
            ],
            options={
                'verbose_name': 'Alert',
                'ordering': ['-created_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['alert_type', 'is_resolved'], name='mother_aler_alert_t_ac9711_idx'), models.Index(fields=['priority', '-created_at'], name='mother_aler_priorit_7e97fa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('total_registrations', models.PositiveIntegerField(default=0)),
                ('new_registrations', models.PositiveIntegerField(default=0)),
                ('total_anc_visits', models.PositiveIntegerField(default=0)),
                ('completed_visits', models.PositiveIntegerField(default=0)),
                ('missed_visits', models.PositiveIntegerField(default=0)),
                ('high_risk_cases', models.PositiveIntegerField(default=0)),
                ('stable_cases', models.PositiveIntegerField(default=0)),
                ('observation_cases', models.PositiveIntegerField(default=0)),
                ('weekly_registrations', models.JSONField(default=dict)),
                ('visit_target', models.PositiveIntegerField(default=50)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Monthly Report',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='ScheduledVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visit_type', models.CharField(choices=[('anc', 'Antenatal Care'), ('pnc', 'Postnatal Care'), ('followup', 'Follow-up')], default='anc', max_length=10)),
                ('visit_number', models.PositiveIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('completed_visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_for', to='mother.ancvisit')),
                ('mother', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_visits', to='accounts.motherprofile')),
            ],
            options={
                'verbose_name': 'Scheduled Visit',
                'ordering': ['scheduled_date', 'scheduled_time'],
                'abstract': False,
                'indexes': [models.Index(fields=['scheduled_date', 'is_completed'], name='mother_sche_schedul_bee182_idx')],
            },
        ),
    ]
