# Generated by Django 5.2.11 on 2026-02-23 07:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_motherprofile_emergency_contact"),
        ("mother", "0002_alert_monthlyreport_scheduledvisit"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SOSEmergency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "offline_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Client-generated UUID for offline deduplication",
                        unique=True,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("moderate", "Moderate"),
                            ("low", "Low"),
                        ],
                        default="critical",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active — Awaiting Response"),
                            ("responding", "Responder En Route"),
                            ("resolved", "Resolved"),
                            ("cancelled", "Cancelled / False Alarm"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS latitude captured at SOS trigger time",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="GPS longitude captured at SOS trigger time",
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="Brief emergency description"
                    ),
                ),
                (
                    "triggered_at",
                    models.DateTimeField(
                        help_text="Client-side timestamp (may differ from created_at if the device was offline)"
                    ),
                ),
                (
                    "is_synced",
                    models.BooleanField(
                        default=True,
                        help_text="False while queued offline; set True once server confirms",
                    ),
                ),
                (
                    "synced_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp of successful server sync",
                        null=True,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                (
                    "mother",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sos_emergencies",
                        to="accounts.motherprofile",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_sos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="FCHV who pressed the SOS button",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_sos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SOS Emergency",
                "verbose_name_plural": "SOS Emergencies",
                "ordering": ["-created_at"],
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["status", "-triggered_at"],
                        name="mother_sose_status_f7f87c_idx",
                    ),
                    models.Index(
                        fields=["mother", "-triggered_at"],
                        name="mother_sose_mother__01a1b8_idx",
                    ),
                    models.Index(
                        fields=["offline_id"], name="mother_sose_offline_66d6bb_idx"
                    ),
                ],
            },
        ),
    ]
