# Generated by Django 5.2.11 on 2026-02-23 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="motherprofile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Mother Profile",
                "verbose_name_plural": "Mother Profiles",
            },
        ),
        migrations.RemoveField(
            model_name="motherprofile",
            name="tracking_method",
        ),
        migrations.RemoveField(
            model_name="motherprofile",
            name="user",
        ),
        migrations.AddField(
            model_name="motherprofile",
            name="medical_notes",
            field=models.TextField(
                blank=True, help_text="Basic medical history / pre-existing conditions"
            ),
        ),
        migrations.AddField(
            model_name="motherprofile",
            name="phone",
            field=models.CharField(blank=True, help_text="Optional", max_length=20),
        ),
        migrations.AddField(
            model_name="motherprofile",
            name="registered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="FCHV who registered this mother",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="registered_mothers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="motherprofile",
            name="pregnancy_week",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Gestational week at time of registration",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("healthcare_worker", "Healthcare Worker"),
                    ("admin", "Admin"),
                ],
                default="healthcare_worker",
                max_length=20,
            ),
        ),
    ]
