# Generated by Django 5.2.8 on 2026-02-23 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_age_user_education_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='photo',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='mothers/photos/'),
        ),
    ]
