# Generated by Django 5.2.8 on 2026-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_motherprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, help_text='Family / emergency contact phone number', max_length=20),
        ),
    ]
