# Generated by Django 5.2.11 on 2026-02-22 16:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=300, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nutrition", "Nutrition & Diet"),
                            ("exercise", "Exercise & Fitness"),
                            ("danger_signs", "Danger Signs"),
                            ("birth_prep", "Birth Preparedness"),
                            ("postpartum", "Postpartum Care"),
                            ("mental_health", "Mental Health"),
                            ("breastfeeding", "Breastfeeding"),
                            ("general", "General Health"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "trimester",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "All Trimesters"),
                            (1, "First Trimester"),
                            (2, "Second Trimester"),
                            (3, "Third Trimester"),
                        ],
                        default=0,
                    ),
                ),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="education/"),
                ),
                ("is_published", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Education Content",
                "verbose_name_plural": "Education Content",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PregnancyMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField(unique=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(help_text="What's happening this week."),
                ),
                (
                    "baby_size",
                    models.CharField(
                        blank=True, help_text="e.g. 'Size of a mango'", max_length=100
                    ),
                ),
                (
                    "tips",
                    models.TextField(
                        blank=True, help_text="Health tips for this week."
                    ),
                ),
                (
                    "trimester",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "First"), (2, "Second"), (3, "Third")]
                    ),
                ),
            ],
            options={
                "verbose_name": "Pregnancy Milestone",
                "ordering": ["week_number"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("reason", models.TextField(help_text="Reason for consultation.")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("doctor_notes", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consultation_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Consultation Request",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DangerSignReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "danger_sign",
                    models.CharField(
                        choices=[
                            ("heavy_bleeding", "Heavy vaginal bleeding"),
                            ("severe_headache", "Severe, persistent headache"),
                            ("blurred_vision", "Blurred vision / Seeing spots"),
                            ("high_fever", "High fever (>38°C / 100.4°F)"),
                            ("severe_abdominal_pain", "Severe abdominal pain"),
                            ("convulsions", "Convulsions / Fits"),
                            ("reduced_fetal_movement", "No / Reduced fetal movement"),
                            ("water_break", "Water breaking before term"),
                            ("severe_swelling", "Severe swelling of face/hands"),
                            ("difficulty_breathing", "Difficulty breathing"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="More details about the sign."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewed", "Reviewed by FCHV"),
                            ("escalated", "Escalated to Doctor"),
                            ("resolved", "Resolved"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_danger_signs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="danger_sign_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Danger Sign Report",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Spouse / Partner"),
                            ("parent", "Parent"),
                            ("sibling", "Sibling"),
                            ("friend", "Friend"),
                            ("doctor", "Doctor"),
                            ("health_facility", "Health Facility"),
                            ("ambulance", "Ambulance Service"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                ("alternate_phone", models.CharField(blank=True, max_length=20)),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False, help_text="Primary emergency contact."
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="emergency_contacts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Emergency Contact",
                "ordering": ["-is_primary", "name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reminder_type",
                    models.CharField(
                        choices=[
                            ("anc_visit", "ANC Visit"),
                            ("medication", "Medication / Supplement"),
                            ("vaccination", "Vaccination"),
                            ("checkup", "Doctor Check-up"),
                            ("custom", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Reminder",
                "ordering": ["due_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SymptomLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "symptom",
                    models.CharField(
                        choices=[
                            ("nausea", "Nausea / Morning sickness"),
                            ("headache", "Headache"),
                            ("fatigue", "Fatigue / Tiredness"),
                            ("back_pain", "Back pain"),
                            ("swelling", "Swelling (feet/hands/face)"),
                            ("dizziness", "Dizziness"),
                            ("heartburn", "Heartburn / Acidity"),
                            ("cramps", "Abdominal cramps"),
                            ("bleeding", "Vaginal bleeding"),
                            ("reduced_movement", "Reduced fetal movement"),
                            ("high_bp", "High blood pressure symptoms"),
                            ("fever", "Fever"),
                            ("vision_changes", "Blurred vision / Seeing spots"),
                            ("shortness_breath", "Shortness of breath"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Mild"),
                            (2, "Moderate"),
                            (3, "Noticeable"),
                            (4, "Severe"),
                            (5, "Very Severe"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Describe the symptom."),
                ),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="symptom_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Symptom Log",
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vaccine_name",
                    models.CharField(
                        choices=[
                            ("tt1", "Tetanus Toxoid - 1st dose (TT1)"),
                            ("tt2", "Tetanus Toxoid - 2nd dose (TT2)"),
                            ("tt3", "Tetanus Toxoid - 3rd dose (TT3)"),
                            ("td1", "Tetanus Diphtheria - 1st dose (Td1)"),
                            ("td2", "Tetanus Diphtheria - 2nd dose (Td2)"),
                            ("covid", "COVID-19 Vaccine"),
                            ("influenza", "Influenza Vaccine"),
                            ("hepatitis_b", "Hepatitis B Vaccine"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("administered_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "administered_by",
                    models.CharField(
                        blank=True, help_text="Name of health worker.", max_length=200
                    ),
                ),
                (
                    "facility",
                    models.CharField(
                        blank=True, help_text="Health facility name.", max_length=200
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Vaccination Record",
                "ordering": ["scheduled_date"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HealthStreak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("took_vitamins", models.BooleanField(default=False)),
                ("exercised", models.BooleanField(default=False)),
                ("drank_water", models.BooleanField(default=False)),
                ("ate_balanced_meal", models.BooleanField(default=False)),
                ("slept_well", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_streaks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Health Streak",
                "ordering": ["-created_at"],
                "abstract": False,
                "unique_together": {("user", "date")},
            },
        ),
    ]
